### ISSUE TITLE
这是什么博客

### ISSUE THREAD

**Issue by zhangwei900808** [VaJoy/BlogDemo2#1]
大神，还记得我吗，我是微博里的'耀一世界的彩’，你这个博客是干嘛用的，有网址可以预览下吗

**Comment by VaJoy** [comment]
@zhangwei900808 只是用来放置我[博客园博客](http://vajoy.cnblogs.com/)文章demo的仓库罢了啊

**Comment by zhangwei900808** [comment]
哦哦，为什么你不搞个自己的网站呢，不是有github pages吗
